# Generated by Django 5.2.5 on 2025-08-19 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notificationtemplate_alter_notification_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NotificationTemplate',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='is_email_sent',
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('booking', 'Booking'), ('payment', 'Payment'), ('admin', 'Admin'), ('system', 'System')], default='system', max_length=20),
        ),
        migrations.DeleteModel(
            name='UserNotificationPreference',
        ),
    ]
